services:
  postgres:
    image: postgres:16-alpine
    container_name: hospital_ticket_db
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ticket_admin
      POSTGRES_PASSWORD: "HspDb_7nQ4wR9xK2mP5vL8"
      POSTGRES_DB: hospital_tickets
    command:
      - postgres
      - -c
      - max_connections=200
      - -c
      - shared_buffers=256MB
      - -c
      - statement_timeout=15000
      - -c
      - idle_in_transaction_session_timeout=30000
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ticket_admin -d hospital_tickets"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: hospital_ticket_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
  redis_data:
