export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",

  UNAUTHORIZED: "UNAUTHORIZED",

  FORBIDDEN: "FORBIDDEN",

  NOT_FOUND: "NOT_FOUND",

  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;
